# Generated by Django 5.1.4 on 2026-06-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_question_options_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='classification',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.questionnaire'),
        ),
    ]
