# Generated by Django 5.1.4 on 2026-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_classification_assessment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='respondent_mode',
            field=models.CharField(choices=[('staff', 'Staff'), ('child', 'Child')], default='staff', max_length=10),
        ),
    ]
