# Generated by Django 5.1.4 on 2026-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_respondent_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='concern_direction',
            field=models.CharField(choices=[('higher', 'Higher'), ('lower', 'Lower')], default='higher', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='concern_options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
