# Generated by Django 5.1.4 on 2026-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_question_concern_direction_question_concern_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_confidence_threshold', models.PositiveSmallIntegerField(default=80)),
                ('require_override_on_low_confidence', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_analysis_setting',
            },
        ),
    ]
