# Generated by Django 5.1.4 on 2026-06-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_analysissetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='overridden',
            field=models.BooleanField(default=False),
        ),
    ]
