# Generated by Django 5.1.4 on 2026-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_questionnaire_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
