# Generated by Django 5.1.4 on 2026-07-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessment_is_locked_assessment_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='next_session',
            field=models.DateField(blank=True, null=True),
        ),
    ]
