# Generated by Django 5.1.4 on 2026-06-26 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived'), ('login', 'Login')], max_length=20)),
                ('category', models.CharField(choices=[('record', 'Record'), ('user', 'User'), ('security', 'Security')], max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
