# Generated by Django 5.1.4 on 2026-06-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_child_assigned_psychologist_location_surrendered'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='assignee_sees_history',
            field=models.BooleanField(default=True),
        ),
    ]
